src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
    private $confirm_password;

    /**
     * @ORM\Column(type="string", length=255,unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fullName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $job;

    /**
     * @ORM\OneToMany(targetEntity=UserPhoto::class, mappedBy="user")
     */
    private $userPhotos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adress;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="myFrinds")
     */
    private $Frinds;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="Frinds")
     */
    private $myFrinds;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="userSend")
     */
    private $messagesSend;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="userReceved")
     */
    private $messagesReceved;

    /**
     * @ORM\OneToMany(targetEntity=MessageVu::class, mappedBy="user")
     */
    private $messageVus;

    public function __construct()
    {
        $this->userPhotos = new ArrayCollection();
        $this->Frinds = new ArrayCollection();
        $this->myFrinds = new ArrayCollection();
        $this->messagesSend = new ArrayCollection();
        $this->messagesReceved = new ArrayCollection();
        $this->messageVus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
//        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }  public function getConfirmPassword(): string
    {
        return (string) $this->confirm_password;
    }

    public function setConfirmPassword(string $password): self
    {
        $this->confirm_password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(?string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(?string $job): self
    {
        $this->job = $job;

        return $this;
    }

    /**
     * @return Collection|UserPhoto[]
     */
    public function getUserPhotos(): Collection
    {
        return $this->userPhotos;
    }

    public function addUserPhoto(UserPhoto $userPhoto): self
    {
        if (!$this->userPhotos->contains($userPhoto)) {
            $this->userPhotos[] = $userPhoto;
            $userPhoto->setUser($this);
        }

        return $this;
    }

    public function removeUserPhoto(UserPhoto $userPhoto): self
    {
        if ($this->userPhotos->removeElement($userPhoto)) {
            // set the owning side to null (unless already changed)
            if ($userPhoto->getUser() === $this) {
                $userPhoto->setUser(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getFrinds(): Collection
    {
        return $this->Frinds;
    }

    public function addFrind(self $frind): self
    {
        if (!$this->Frinds->contains($frind)) {
            $this->Frinds[] = $frind;
        }else{
            $this->Frinds->removeElement($frind);
        }

        return $this;
    }

    public function removeFrind(self $frind): self
    {
        $this->Frinds->removeElement($frind);

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getMyFrind(): Collection
    {
        return $this->myFrinds;
    }

    public function addMyFrind(self $user): self
    {
        if (!$this->myFrinds->contains($user)) {
            $this->myFrinds[] = $user;
            $user->addFrind($this);
        }

        return $this;
    }

    public function removeMyFrind(self $user): self
    {
        if ($this->myFrinds->removeElement($user)) {
            $user->removeFrind($this);
        }

        return $this;
    }

    public function isFrind( $user): bool {
        if ($this->Frinds->contains($user)) {
            return true;
        }else{
            return false;
        }
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessagesSend(): Collection
    {
        return $this->messagesSend;
    }

    public function getMessagesSendBy($id)
    {

        $messages_t =  $this->messagesSend;
        $messages = new ArrayCollection();
        foreach ($messages_t as $value){
            if ($value->getUserReceved()->getId() == $id){
                $messages->add($value);
            }
        }
        return $messages;
    }

    public function addMessagesSend(Message $messagesSend): self
    {
        if (!$this->messagesSend->contains($messagesSend)) {
            $this->messagesSend[] = $messagesSend;
            $messagesSend->setUserSend($this);
        }

        return $this;
    }

    public function removeMessagesSend(Message $messagesSend): self
    {
        if ($this->messagesSend->removeElement($messagesSend)) {
            // set the owning side to null (unless already changed)
            if ($messagesSend->getUserSend() === $this) {
                $messagesSend->setUserSend(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessagesReceved(): Collection
    {
        return $this->messagesReceved;
    }

    public function addMessagesReceved(Message $messagesReceved): self
    {
        if (!$this->messagesReceved->contains($messagesReceved)) {
            $this->messagesReceved[] = $messagesReceved;
            $messagesReceved->setUserReceved($this);
        }

        return $this;
    }

    public function removeMessagesReceved(Message $messagesReceved): self
    {
        if ($this->messagesReceved->removeElement($messagesReceved)) {
            // set the owning side to null (unless already changed)
            if ($messagesReceved->getUserReceved() === $this) {
                $messagesReceved->setUserReceved(null);
            }
        }

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta
            name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link
            rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
    <title>
        MySite |
        {% block title %}{% endblock %}
    </title>
    {# Run `composer require symfony/webpack-encore-bundle`
                       and uncomment the following Encore helpers to start using Symfony UX #}
    {% block stylesheets %}
        {#{{ encore_entry_link_tags('app') }}#}
    {% endblock %}

    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    {% block javascripts %}
        {#{{ encore_entry_script_tags('app') }}#}
    {% endblock %}
</head>
<style>
    .style_body{
        height: 700px;
        display: block;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;

        background-image: linear-gradient(rgba(255,255,255,0.9),rgba(0,0,0,0.8)), url('../../dist/img/photo4.jpg');
    }
    .style_contenu {
        margin: 20px;
        padding: 10px;
        background-color: rgba(255,255,255,0.4);
    }
</style>
<body class="style_body">
{% include "navBar.html.twig"  %}
{% include "sideBar.html.twig"  %}
<div class="content-wrapper style_contenu">


{% block body %}
{% endblock %}
</div>
</body>

</html>
</div></body>
{#<script src="../../dist/js/demo.js"></script></html>#}

templates/base_login.html.twig
<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta
                name="viewport" content="width=device-width, initial-scale=1">
        <!-- Font Awesome -->
        <link
                rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
{#        <!-- Theme style -->#}
        <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
        <title>
            MySite |
            {% block title %}{% endblock %}
        </title>
        {# Run `composer require symfony/webpack-encore-bundle`
                           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        <!-- jQuery -->
        <script src="../../plugins/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
{#        <script src="../../dist/js/adminlte.min.js"></script>#}
        <!-- AdminLTE for demo purposes -->
        {% block javascripts %}

        {% endblock %}
        <style>
            .style_body{
                height: 700px;
                display: block;
                background-repeat: no-repeat;
                background-size: cover;
                background-position: center;
                background-attachment: fixed;

                background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.9)), url('../../dist/img/photo4.jpg');
            }
        </style>

    </head>


    <body class="style_body" style="height: 100%" >
        {% block body %}{% endblock %}
    </body>
</html>

templates/navBar.html.twig
<div class="wrapper">


<nav class="main-header navbar navbar-expand nnavbar-white navbar-light" style="background-color: rgba(0,0,0,0.5)">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
{#        <li class="nav-item d-none d-sm-inline-block">#}
{#            <a href="../../index3.html" class="nav-link">Home</a>#}
{#        </li>#}
{#        <li class="nav-item d-none d-sm-inline-block">#}
{#            <a href="#" class="nav-link">Contact</a>#}
{#        </li>#}
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->


        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">{{ app.user.allNewMessage(app.user.id)['messages'] | length }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right " >
                {% for user in app.user.allNewMessage(app.user.id)['users']   %}
                <a href="{{ path('message_new', {'name': user.name}) }}" class="dropdown-item ">
                    <!-- Message Start -->

                    <div class="media">
                        <img src="/uploads/images/users/profil{{user.photo ? asset(user.photo) : '/avatar.png' }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                {{ user.name }}
                                <span class="float-right text-sm text-danger"><i class="fas fa-mail-bulk"></i>{{ user.NewMessage(app.user.id) | length }}</span>
                            </h3>
                            <p class="text-sm">{{ user.NewMessage(app.user.id)[user.NewMessage(app.user.id)|length -1].message }}</p>
                            <p class="text-sm text-muted "><i class="far fa-clock mr-1"></i> {{ user.NewMessage(app.user.id)[user.NewMessage(app.user.id) | length -1].sendAt |date('Y-m-d H:i:s')   }}</p>

                        </div>
                    </div>
                    <!-- Message End -->

                </a>

                        <div class="dropdown-divider"></div>
                {% endfor %}
                <div class="dropdown-divider"></div>
                <a href="{{ path('all_message_index') }}" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
{#        <li class="nav-item dropdown">#}
{#            <a class="nav-link" data-toggle="dropdown" href="#">#}
{#                <i class="far fa-bell"></i>#}
{#                <span class="badge badge-warning navbar-badge">15</span>#}
{#            </a>#}
{#            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">#}
{#                <span class="dropdown-item dropdown-header">15 Notifications</span>#}
{#                <div class="dropdown-divider"></div>#}
{#                <a href="#" class="dropdown-item">#}
{#                    <i class="fas fa-envelope mr-2"></i> 4 new messages#}
{#                    <span class="float-right text-muted text-sm">3 mins</span>#}
{#                </a>#}
{#                <div class="dropdown-divider"></div>#}
{#                <a href="#" class="dropdown-item">#}
{#                    <i class="fas fa-users mr-2"></i> 8 friend requests#}
{#                    <span class="float-right text-muted text-sm">12 hours</span>#}
{#                </a>#}
{#                <div class="dropdown-divider"></div>#}
{#                <a href="#" class="dropdown-item">#}
{#                    <i class="fas fa-file mr-2"></i> 3 new reports#}
{#                    <span class="float-right text-muted text-sm">2 days</span>#}
{#                </a>#}
{#                <div class="dropdown-divider"></div>#}
{#                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>#}
{#            </div>#}
{#        </li>#}
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>
</div>

templates/sideBar.html.twig
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color: rgba(0,0,0,0.5)">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
        <img src="../../dist/img/AdminLTELogo.png" alt=" Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">My Site</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="/uploads/images/users/profil{{app.user.photo ? asset(app.user.photo) : '/avatar.png' }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{{ path('user_show',{'name':app.user.name}) }}" class="d-block">{{ app.user.name }}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
            <div class="sidebar-search-results"><div class="list-group"><a href="#" class="list-group-item">
                        <div class="search-title">
                            <b class="text-light"></b>N<b class="text-light"></b>o<b class="text-light"></b> <b class="text-light"></b>e<b class="text-light"></b>l<b class="text-light"></b>e<b class="text-light"></b>m<b class="text-light"></b>e<b class="text-light"></b>n<b class="text-light"></b>t<b class="text-light"></b> <b class="text-light"></b>f<b class="text-light"></b>o<b class="text-light"></b>u<b class="text-light"></b>n<b class="text-light"></b>d<b class="text-light"></b>!<b class="text-light"></b>
                        </div>
                        <div class="search-path">

                        </div>
                    </a></div></div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Amis
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ path('user_index') }}" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Trouver des amis
                                    <span class="right badge badge-danger">New</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ path('suivie_index') }}" class="nav-link">
                                <i class="text-blue nav-icon fas fa-users"></i>
                                <p>
                                    suivies
                                    <span class="right badge badge-info">{{ app.user.frinds | length }}</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ path('abonnee_index') }}" class="nav-link">
                                <i class="text-red nav-icon fas fa-users"></i>
                                <p>
                                    Abonnees
                                    <span class="right badge badge-info">{{ app.user.MyFrind | length }}</span>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{ path('all_message_index') }}" class="nav-link">
                        <i class="nav-icon fas fa-envelope"></i>
                        <p>
                            Messages
                            <span class="right badge badge-danger ">{{ app.user.allNewMessage(app.user.id)['messages'] | length }}</span>
{#                            <span class="right badge badge-danger">New</span>#}
                        </p>
                    </a>
                </li>
{#                <li class="nav-item">#}
{#                    <a href="{{ path('user_index') }}" class="nav-link">#}
{#                        <i class="nav-icon fas fa-users"></i>#}
{#                        <p>#}
{#                            Trouver des amis#}
{#                            <span class="right badge badge-danger">New</span>#}
{#                        </p>#}
{#                    </a>#}
{#                </li>#}


            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>